/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_advance_home12.gradle;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
